robots:
  cf_1:
    enabled: true
    uri: udp://0.0.0.0:19850
    initial_position:
      - 0
      - 0
      - 0
    type: cf_sim
    intial_position:
      - 0
      - 1
      - 0
  cf_2:
    enabled: true
    uri: udp://0.0.0.0:19851
    initial_position:
      - 0
      - 0
      - 0
    type: cf_sim
    intial_position:
      - 0
      - 0
      - 0
  cf_3:
    enabled: false
    uri: udp://0.0.0.0:19852
    initial_position:
      - 2
      - 0
      - 0
    type: cf_sim
    intial_position:
      - 2
      - 1
      - 0
  cf_4:
    enabled: false
    uri: udp://0.0.0.0:19853
    initial_position:
      - 0
      - 1
      - 0
    type: cf_sim
    intial_position:
      - 0
      - 0
      - 0
  cf_5:
    enabled: false
    uri: udp://0.0.0.0:19854
    initial_position:
      - 1
      - 1
      - 0
    type: cf_sim
    intial_position:
      - 1
      - 0
      - 0
  cf_6:
    enabled: false
    uri: udp://0.0.0.0:19855
    initial_position:
      - 1
      - 0
      - 0
    type: cf_sim
    intial_position:
      - 0
      - 0
      - 0
  cf_7:
    enabled: false
    uri: udp://0.0.0.0:19856
    initial_position:
      - 1
      - 1
      - 0
    type: cf_sim
    intial_position:
      - 1
      - 0
      - 0
  cf_8:
    enabled: false
    uri: udp://0.0.0.0:19857
    initial_position:
      - 1
      - 2
      - 0
    type: cf_sim
    intial_position:
      - 2
      - 0
      - 0
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
    big_quad: false
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 50
        twist:
          frequency: 50
      custom_topics:
        velocity:
          frequency: 50
          vars:
            - kalman.statePX
            - kalman.statePY
            - kalman.statePZ
        angular_velocity:
          frequency: 50
          vars:
            - gyro.x
            - gyro.y
            - gyro.z
  cf:
    motion_capture:
      enabled: true
      marker: cf_mpc
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 100
      custom_topics:
        velocity:
          frequency: 100
          vars:
            - kalman.statePX
            - kalman.statePY
            - kalman.statePZ
        angular_velocity:
          frequency: 100
          vars:
            - gyro.x
            - gyro.y
            - gyro.z
  cf_mocap_deck:
    motion_capture:
      enabled: true
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7
all:
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 1
    locSrv:
      extPosStdDev: 0.001
      extQuatStdDev: 0.05
  broadcasts:
    num_repeats: 15
    delay_between_repeats_ms: 1
